title: Shouvik Sharma # your name (or website title) here
logo: "/images/linkedin_profile_pic.jfif?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  First description 
  Passionate about data science | I like to answer your questions with the data
  <br><br>
  Second description 
  Realized data science had two important aspects :-
  1) Computer Science
  2) Mathematics
  That's why did my Masters in Statistics and currently pursuing Master of Data Science :-
MASTER OF DATA SCIENCE
ILLINOIS INSTITUTE OF TECHNOLOGY
August 2019 – Present
Chicago, USA
• GPA: 3.71

MASTER OF STATISTICS
NMIMS
July 2016 – April 2018
Mumbai, India
• GPA: 3.35
  <br><br>
  <a href="https://www.linkedin.com/in/example/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
